### ISSUE TITLE
Is it possible to configure and modifier key for the zoom / pan ?

### ISSUE THREAD

**Issue by jexp** [anvaka/panzoom#1]
Really cool library, worked smoothly out of the box !! And the SVG keeps all its interactivity.

Usually zooming interferes with scrolling so often people use a modifier key like shift or option for the zoom / pan operation.

Would it be possible to add that to the panzoom call as an optional config?

**Comment by anvaka** [comment]
Good suggestion. Thank you Michael!

I added `beforeFilter` callback, so that clients can decide when to ignore `mousewheel` event. Please let me know if this works.

**Comment by jexp** [comment]
Works perfect, thanks !!
