### ISSUE TITLE
How do you edit those documents?

### ISSUE THREAD

**Issue by josephernest** [anvaka/panzoom#101]
Would you have a version with an editor?

How do you edit them yourself?

**Comment by rbonomo** [comment]
What documents are you referring to?

**Comment by josephernest** [comment]
I mean a way to edit those pages like a whiteboard / infinite notepad where
you can click and type text or copy/paste images?

How do you currently do those example pages? With a text editor and
directly on html ?

>

**Comment by rbonomo** [comment]
What pages are you referring to?

**Comment by anvaka** [comment]
@josephernest we are missing some context here. Could you please give a link to a page?

**Comment by anvaka** [comment]
no response, closing

**Comment by josephernest** [comment]
Sorry for delay @anvaka. I mean to create pages like [this](https://anvaka.github.io/panzoom/demo/index.html) one, you probably don't want to do it manually with a text editor directly on the HTML code. Would you have a version with contenteditable fields to make it editable?

**Comment by anvaka** [comment]
Oh if you need to generate page like that, please check out https://www.yasiv.com
