### ISSUE TITLE
Older Android WebView Versions Support

### ISSUE THREAD

**Issue by rbonomo** [anvaka/panzoom#102]
This is a continuation of the discussion in #100. The built JS from panzoom uses Set, which is not defined in some older versions of Android Webview (API level 19, Android KitKat, lower-bound of 95% Android device support). Also, requestAnimationFrame is not defined as well. Would be awesome if this lib had a build process that polyfilled these undefineds for mobile browser support.

**Comment by anvaka** [comment]
To be honest, I think polyfilling should happen on consumer side, not in the library.

Reason for that is that once a better version of polyfill comes out - there is no need to update the library. Also putting polyfills into the library limits dynamic polyfilling (i.e. download bundle with polyfills only when certain functionality is not supported by runtime - that reduces amount of bytes transferred for a happy case) 

For those who need this library to work in older android webviews, please use the following polyfills before using the library:

* https://gist.github.com/paulirish/1579671 - `requestAnimationFrame`
* https://github.com/jfriend00/ES6-Set/blob/master/set.js - `Set`

**Comment by rbonomo** [comment]
Good points! Thanks for you input.
