### ISSUE TITLE
Limit boundary to image max?

### ISSUE THREAD

**Issue by kuzziemon** [anvaka/panzoom#105]
Is it possible to limit zoom and pan to the image resolution?
I want to be able to zoom in and pan as if the boundaries are that of the image itself.

I've tried tinkering with the bounds option to no avail, so if I'm missing something blatantly obvious, please correct me.

**Comment by rbonomo** [comment]
Is this your problem?
https://codepen.io/rbonomo/pen/QRaRBN

Is this what you want?
https://codepen.io/rbonomo/pen/VOQwWZ
This pen uses the dist js in PR #106

**Comment by rbonomo** [comment]
Can you post a codepen of what you have and I will get you where you want to go. I'm not understanding "limits of the boundaries to be the max of the ratio of height or width".

**Comment by kuzziemon** [comment]
https://codepen.io/anon/pen/dEdqBR

Say I need the image to be side a div that's 500x500 and the image itself is 3000x5000.
I need it to fit to the maximum side(in this case the height), so it will have bars on the side and prevent the panning until the image is zoomed in enough to allow space for panning up and down within the image itself.

**Comment by kuzziemon** [comment]
The autocenter() function draws it perfectly.
I need whatever autocenter generates as the bounding box, but still allow zooming in and panning within that boundary.

Also, unrelated issue but it seems that there is something wrong with the animate() function when you use scroll wheel. I've noticed the same issue when using smoothZoom. It will get hung up on the animation and cause stuttering effects when used in quick succession.

**Comment by rbonomo** [comment]
Is this what you're looking for?
https://codepen.io/rbonomo/pen/BexEPR

**Comment by rbonomo** [comment]
@kuzziemon you'll probably have to call the kinetic.cancel() function before using any animate functions to prevent that from happening. Look in the source code.

**Comment by kuzziemon** [comment]
I see, thanks for your help. 
I've opted for another library with a bit more robust features, but this is still good to know as it still does apply.

**Comment by rbonomo** [comment]
@kuzziemon What library did you go forward with?

**Comment by bbugh** [comment]
@kuzziemon what library did you use?

**Comment by Andrew-web-coder** [comment]
The only one I could find is this one - https://fancyapps.com/docs/ui/panzoom/
