### ISSUE TITLE
How to prevent an event from happening?

### ISSUE THREAD

**Issue by jnwelzel** [anvaka/panzoom#107]
As an example, I would like to prevent the `panstart` from happening at all in case the zoom scale is 1. But I couldn't find a way to prevent the event from happening, like say, a `event.preventDefault()`.

**Comment by rbonomo** [comment]
```
const handleMouseMove = event => {
  event.stopPropagation()
  ...
}

somePanzoomChildHTMLElement.addEventListener('mousemove', handleMouseMove)
```

**Comment by jnwelzel** [comment]
Thank you @rbonomo
