### ISSUE TITLE
Is there a way to  stop Image from panning out of the view without resetting Zoom?

### ISSUE THREAD

**Issue by dota2Pro** [anvaka/panzoom#114]
Stackoverflow post

https://stackoverflow.com/questions/56908684/panzoom-how-to-stop-image-from-panning-out-of-the-view

Is it possible to bounce the image back if its about to disappear while panning out of the view? just like a OS's image viewer ?

**Comment by rbonomo** [comment]
look into the code and use the bounds and boundsPadding configs.
