### ISSUE TITLE
Keep getting this error in browser console

### ISSUE THREAD

**Issue by dota2Pro** [anvaka/panzoom#118]
Using Chrome latest 74 desktop Windows 10

![image](https://user-images.githubusercontent.com/48334588/61544563-bc31ed80-aa13-11e9-975f-f9993d09ec2e.png)

Error comes from domController.js 
`  domElement.scrollTop = 0;`
![image](https://user-images.githubusercontent.com/48334588/61544697-f7ccb780-aa13-11e9-8025-bfaeb78a3732.png)

using
```

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cdk                      8.0.1
@angular/cli                      8.0.6
@angular/material                 8.0.1
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
    "panzoom": "^8.1.0",

```

**Comment by rbonomo** [comment]
Look at your URL man. Then look at the HTTP status code you are getting.

https://mywebsite.com/undefined ???

**Comment by dota2Pro** [comment]
> Look at your URL man. Then look at the HTTP status code you are getting.
> 
> https://mywebsite.com/undefined ???

This is generated by the library my app runs fine on the server

**Comment by rbonomo** [comment]
You've got some bundling process going on as your vendor.js file is 14k lines long. Your chrome debugger is probably wiggin out and the error isn't actually occurring there. Try to just include panzoom with a script tag, take it our of your bundle, and see if you still get the error.
