### ISSUE TITLE
Links don't work on mobile

### ISSUE THREAD

**Issue by StipeP** [anvaka/panzoom#119]
Can I just say that I have no working knowledge of js yet. I'm putting things together in hope it will work. 

Anyway, if I open a page on mobile, links don't work. I can touch as much as I want, but all it will ever do is zoom-in if I double-touch quickly. Try opening this on mobile https://anvaka.github.io/panzoom/demo/attach-via-script.html

What do I add or comment-out to get the links working? Thanks

**Comment by sookoll** [comment]
Can confirm, links not work.

**Comment by sookoll** [comment]
Ok, they work, I just missed that section on README. I pull repo, dig into code and found reference to https://github.com/anvaka/panzoom/issues/12#issuecomment-373251144 and from that I found it on README also. So it is documented and links work on touch devices, if You add onTouch option.

**Comment by StipeP** [comment]
> Ok, they work, I just missed that section on README. I pull repo, dig into code and found reference to [#12 (comment)](https://github.com/anvaka/panzoom/issues/12#issuecomment-373251144) and from that I found it on README also. So it is documented and links work on touch devices, if You add onTouch option.

Please help :)
Where exactly do I paste this? On which line, in which form? 

panzoom(element, {
  onTouch: function(e) {
    // `e` - is current touch event.

    return false; // tells the library to not preventDefault.
  }
});

Like I said, I'm a total js noob and all of this is way beyond my level.

**Comment by sookoll** [comment]
You should set this as property when You initialize panzoom:

```
const pz = panzoom('.mydiv', {
  ...
  onTouch: e => {
    // `e` - is current touch event.
    return false; // tells the library to not preventDefault.
  }
});

```

**Comment by StipeP** [comment]
> You should set this as property when You initialize panzoom:
Yeah, those are some English words, but I don't know what does that mean :)

Is there anything I can edit in dist/panzoom.js to make it work, and if so, on which line? Or that's just not how these things work.

**Comment by sookoll** [comment]
Where and how do You want to use this library? You have some container in html where You want to add panzoom functionality? Than You have this library installed as npm module or added to page as script tag? Like here described: https://github.com/anvaka/panzoom#usage
Then You have to initialise panzoom, right? Like here: https://github.com/anvaka/panzoom#pan-and-zoom-dom-subtree
And if you want to change panzoom behaviour, like to set links to work on mobile, You can configure it with properties. So, instead:
```
// just grab a DOM element
var element = document.querySelector('#scene')

// And pass it to panzoom
panzoom(element)
```

You should do that:
```
// just grab a DOM element
var element = document.querySelector('#scene')

// And pass it to panzoom
panzoom(element, {
  onTouch: e => {
    return false;
  }
})
```
Hope that helps. If not, try to learn a JS basics before.

**Comment by StipeP** [comment]
> Hope that helps. If not, try to learn a JS basics before.

I did learn JS basics and that was all about making to-do application in console. Nothing as complex as this. :)

But I did manage to make it work now. Thanks!

**Comment by sookoll** [comment]
Ok, good. You can now close this issue.
