### ISSUE TITLE
How to handle touch events?

### ISSUE THREAD

**Issue by tracycollins** [anvaka/panzoom#12]
I can't figure out how to get touch events (using the d3.js library) to work.

Is there a way to tell panzoom to ignore touch events?

**Comment by anvaka** [comment]
Are you trying to enable panzoom for existing d3 visualization? Or do you want to disable touch events?

**Comment by tracycollins** [comment]
Using d3, I have panzoom enabled for an svg g element "svgG" and then want to detect touch events on child elements (cirles and text) of the g element ("nodeCircles")

In the code snippet below, the .on("click", nodeClick) works, but the .on("touchStart", nodeClick) does not.

```
var svgG = svgMain.append("g").attr("id", "svgG");

var panzoomElement = document.getElementById("svgG");
panzoom(panzoomElement, { zoomSpeed: 0.030 });

var nodeSvgGroup = svgG.append("svg:g").attr("id", "nodeSvgGroup");

var nodeCircles = nodeSvgGroup.selectAll("circle").data(nodes, function(d){ return d.nodeId; });

nodeCircles.enter().append("circle").attr("nodeId", function(d) { return d.nodeId; })
 .on("click", nodeClick)
 .on("touchstart", nodeClick);
```

**Comment by anvaka** [comment]
I see. Might be relevant to https://github.com/anvaka/panzoom/issues/11 and comments in [this thread](https://github.com/anvaka/panzoom/pull/15/files/c0d454931eb824dc2a662d6891e768534e669327..b77af2ac694123a3602b535a2dbb5e4f64f15542#diff-168726dbe96b3ce427e7fedce31bb0bc). Unless @odai-alali or someone else beats me to it, I can give a callback approach a try later this week or next.

**Comment by anvaka** [comment]
Just pushed the changes. Should be available in version `4.2.0`. Snippet from the readme:

``` js
panzoom(document.getElementById('g4'), {
  onTouch: function(e) {
    // `e` - is current touch event.

    return false; // tells the library to not preventDefault.
  }
});
```

Please let me know if this does not work.

**Comment by tracycollins** [comment]
Yes, it works!  Thanks!

Unrelated, is there a way to programmatically control panzoom?  For instance, something like:

panzoom.setZoomFactor(2.0);

**Comment by tracycollins** [comment]
I guess I don't completely understand handling events, because now that touch events work, zooming with a mouse (actually touchpad on macbook) now does not. 

How can I get both touch events on iOS and zooming with a mouse to work?

**Comment by anvaka** [comment]
@tracycollins sorry - I missed this one.

To set zoom level from code, you'd need to call `panzoom.zoomAbs(clientX, clientY, zoomFactor)`

As for broken zoom with mouse - can you share a jsbin with me?
