### ISSUE TITLE
Unpackage Dist Js File is out of Sync with Codebase

### ISSUE THREAD

**Issue by dota2Pro** [anvaka/panzoom#126]
Just a FYI I was doing to diggin in and found out
that 
https://unpkg.com/panzoom@8.1.1/dist/panzoom.js

has some code removed from
https://github.com/anvaka/panzoom/blob/master/dist/panzoom.js

**Comment by anvaka** [comment]
Thanks for the information. I rebuilt the package and published it as `8.1.2`. The change was just in strict equality: https://github.com/anvaka/panzoom/commit/d2aa9628b5d18490a26300db6b199f5338e60d0c
