### ISSUE TITLE
Is there any way to remove flicking effect in mobile devices

### ISSUE THREAD

**Issue by devxpertyst** [anvaka/panzoom#127]
We are developing mobile app in react native and facing an issue from a long time. Please check the video link at below where svg is not smooth whenever user move this. In browser its working well but in mobile it is worst. 
![2019-08-14_20-51-17](https://user-images.githubusercontent.com/33538137/63034259-998dda00-bed6-11e9-9e95-c8f4133dcde3.gif)

**Comment by anvaka** [comment]
Can you guys create a minimal app to reproduce this?

**Comment by anvaka** [comment]
Might potentially be related to https://github.com/anvaka/panzoom/issues/67

Please let me know if this behavior is still exist in panzoom libraries versioned `8.7.2` and higher.
