### ISSUE TITLE
zoom calculated assuming SVG bounding box is at upper-left of document

### ISSUE THREAD

**Issue by dave-doty** [anvaka/panzoom#132]
I set up three SVG elements, each of which has a panzoom element attached. The top left one (whose upper-left corner is at the upper-left corner of the whole document) zooms as expected.

The other two zoom strangely in the sense that if you position the pointer over a point and zoom in or out, the image does not stay centered as the zoom occurs:

https://jsfiddle.net/9npdksgt/5/

It seems like the effect is due to the zoom transform assuming that the pointer position has been measured relative to the SVG element's origin (upper-left of the bounding box of the SVG element), but instead this transform was given an absolute pointer position for the whole document (whose origin is at the upper-left of the whole window).

**Comment by UnHumbleBen** [comment]
https://github.com/anvaka/panzoom/blob/f1f595fcdea8329994ad028e1fafa359a604c6da/test/panzoom.js#L270-L279

Seems like this line might be the issue. `left` and `right` are always initialized to `0`.

**Comment by dota2Pro** [comment]
Option 1: Move image whenever you zoom like this 
https://stackoverflow.com/questions/57417199/zooming-in-with-keyboard-moves-the-centered-image-to-right 

Option 2: try this library https://timmywil.com/panzoom/demo/ 2nd example

**Comment by anvaka** [comment]
This change should fix the issue: https://github.com/anvaka/panzoom/commit/49be4a1bd6361598b79f29fe99adc2c125d93678

Available starting from `v8.7.3`.

Here is updated version with your example to verify: https://jsfiddle.net/anvaka/ytm52hs8/
