### ISSUE TITLE
Is it possible to programmatically pan and zoom?

### ISSUE THREAD

**Issue by Twitch0125** [anvaka/panzoom#134]
something like this
`
panzoom('#element').panTo(x,y,zoom)
`
and the view would move to the x and y location with the zoom level

**Comment by lucafaggianelli** [comment]
yes that would be very useful

**Comment by dota2Pro** [comment]
you can use .moveTo

**Comment by anvaka** [comment]
Yup, like mentioned above, there are a few options to change pan and zoom programmatically. 

[Readme file](https://github.com/anvaka/panzoom/blob/master/README.md) should have them documented - if you find something missing, please let us know.
