### ISSUE TITLE
Disable animation + Dragging border

### ISSUE THREAD

**Issue by JMD49591** [anvaka/panzoom#136]
Hi,

is there a way to disable the short animation you get when moving the image?

My second concern is a border for maximum/minimum dragging. That you get to a border when trying to move it further. Is there already a way to achieve this behavour? It was not mentioned in the readme, that's why I'm asking.
If not this is gonna be my feature request, for future updates.

**Comment by dota2Pro** [comment]
https://github.com/anvaka/panzoom#disable-smooth-scroll

https://stackoverflow.com/questions/56908684/panzoom-how-to-stop-image-from-panning-out-of-the-view

**Comment by JMD49591** [comment]
It worked, thanks @dota2Pro.
Weird I already tried the disable smooth scroll option, but when I did back then it had no effect. Maybe I did something wrong.
The bounds property was not mentioned in the readme. It should be added imo.
