### ISSUE TITLE
chrome 78.0.3904.87 version problem

### ISSUE THREAD

**Issue by ouze2000** [anvaka/panzoom#139]
After zooming out the Dom containing the canvas,  the pan speed slows down. There was no problem in previous chrome versions. If you turned off hardware acceleration, the problem went away.

**Comment by dota2Pro** [comment]
Please attach reproducible JS Fiddle Demo

**Comment by ouze2000** [comment]
Thank you for your reply.

Here is the JS Fiddle Demo link.

https://jsfiddle.net/ouze2000/oqLa9pk2/3/

2019년 11월 6일 (수) 오전 2:03, dota2Pro <notifications@github.com>님이 작성:

**Comment by dota2Pro** [comment]
You should fix your code, the library is ok see this minimum Canvas example

https://jsfiddle.net/dota2pro/t9qa7gn1/7/

**Comment by ouze2000** [comment]
Thank you for your answer.
But since the purpose is not the zoom of the canvas, but the zoom of
the div that wraps the canvas, I don't think the answer you sent is
the answer.
In previous versions of Chrome, there was no problem, so we contacted Google.
Thank you.


2019년 11월 7일 (목) 오전 12:16, dota2Pro <notifications@github.com>님이 작성:

**Comment by ouze2000** [comment]
Based on the answer from Google.

This fix will be in the M79 stable release in early December but will remain broken in M78 so consider applying the workaround: style="will-change: transform;" on the element with changing transform style. 

Thank you.
