### ISSUE TITLE
Config the drag only happens with right mouse down or left mouse down or wheel down

### ISSUE THREAD

**Issue by zhougch5** [anvaka/panzoom#140]

**Comment by anvaka** [comment]
I'm afraid I don't fully understand the request, but it seems like you want to do the drag with right mouse button or with a wheel button right? 

If this understanding is correct I would be a bit hesitant to add it to the library to not deviate from well-know user experience - right mouse button should be reserved for the context menus.

Please let me know if I'm missing something? What use case are you trying to solve?

**Comment by AskAlice** [comment]
I think he wanted to control what mouse button handles drag events. (ie drag with right mouse button only) 

I have an issue where when I mouseup when I'm done dragging the mouse event bubbles down and fires elsewhere.
