### ISSUE TITLE
Wheel is not disabled on Internet Explorer 11 during pause.

### ISSUE THREAD

**Issue by icithis** [anvaka/panzoom#144]
https://github.com/anvaka/panzoom/blob/8f51e5992b45ff6141b8f3baa972a99167f8f220/dist/panzoom.js#L1669

As properly assumed by the comments, IE 11 does not unsubscribe using this method. Therefore IE 11 always listens to wheel events even when isPaused() returns true.

**Comment by anvaka** [comment]
Thank you for bringing this up. I've [updated the module](https://github.com/anvaka/wheel/commit/11c60dc2b3202fffdfa5f6e09cbe18cccff78652) to use regular `addWheelListener` and verified it is working in IE. Starting from `v8.6.2` you should be able to pause correctly. Please verify?

**Comment by icithis** [comment]
Verified, this fixes my issue in IE11. Thank you for the timely resolution!
