### ISSUE TITLE
How do you properly initiate panzoom in the center of its parent?

### ISSUE THREAD

**Issue by UltraCakeBakery** [anvaka/panzoom#155]
Hi,

I have a canvas element that needs to be in the center of its parent element with the biggest size possible with a 16:9 aspect ratio. It's also zoomed out (0.7)

I call this function after the dom is ready:
```// get wrapper size with padding
            const wrapperWidth = this.$refs.wrapper.offsetWidth
            const wrapperHeight = this.$refs.wrapper.offsetHeight

            let width = 0
            let height = 0

            // Get optimal base width / height
            if ( wrapperWidth * 0.5625 > wrapperHeight )
            {
                width = ( wrapperHeight / 9 ) * 16
                height = wrapperHeight
            }
            else
            {
                width = wrapperWidth
                height = wrapperWidth * 0.5625
            }

            Object.assign( this.$refs.canvas.style, {
                width: `${width}px`,
                height: `${height}px`
            })

            // Setup PanZoom
            this._panzoom = new PanZoom( this.$refs.canvas )

            this._panzoom.moveTo( wrapperWidth / 2 - width / 2, wrapperHeight / 2 - height / 2 )
            this._panzoom.zoomAbs( window.innerWidth / 2, window.innerHeight / 2, 0.7 )
```

This works, however, I don't fancy the fact that I have to call 'moveTo' and 'zoomAbs' right after.
How can I make this work better?

PanZoom overrides the original transform-origin and ignores margins causing unexpected behaviour.

**Comment by BiLosxD** [comment]
Kindly check my solution. https://github.com/anvaka/panzoom/issues/34#issuecomment-553739577

**Comment by UltraCakeBakery** [comment]
Your solution doesn't solve my issue. I don't want to always zoom to the center. I want to initialize the PanZoom element in the center of its parent. I can only do that after initializing panzoom.

Anyways, I switched to https://github.com/timmywil/panzoom

Its smaller in size, more configuration options. typescript, easier to implement.
 I recommend you start using it for your next projects.
