### ISSUE TITLE
Jest unit testing

### ISSUE THREAD

**Issue by sho-87** [anvaka/panzoom#156]
I'm using this library in a React project and having difficulty with setting up a Jest test

I'm creating the panzoom instance fairly basically like this:

    let panZoomContainer = document.querySelector('#tree-square-container');
    panZoomInstance = panzoom(panZoomContainer);

My test looks like this:

```
it('renders without crashing', () => {
    let div = document.createElement('div');
    div.setAttribute('id', 'tree-square-container');
    ReactDOM.render(<TreePanel />, div);
    ReactDOM.unmountComponentAtNode(div);
  });
```
However, I keep getting this error: `Cannot create panzoom for the current type of dom element`

Whats the correct way to set up a test for a React component that uses panzoom? Does something need to be mocked for this to work?

**Comment by inwardmovement** [comment]
I have the same problem, what was the fix?
