### ISSUE TITLE
How do I get the transform values at runtime?

### ISSUE THREAD

**Issue by Forfunckle** [anvaka/panzoom#161]
What are the attributes that change when you zoom/pan? How do I get the scale and position of the element?

**Comment by scaryguy** [comment]
I have the exact question. Couldn't find anything related in the existing API. All events are returning the instance but I can't find a value related to current zoom/pan values.

**Comment by Forfunckle** [comment]
I figured it out. The library modifies the CSS value "style.transform", which is equal to "matrix(sizeX, skewX, skewY, sizeY, posX, posY)". It is a string. I wrote a function that extracts values from the matrix and returns them as separate numbers in order to get the pan/zoom values. P.S. sizeX and sizeY are equal.

**Comment by scaryguy** [comment]
Found it. It was already asked: https://github.com/anvaka/panzoom/issues/39

use `getTransform()` function on any instance variable that you receive in any of the events.

Example:
```javascript
let panzomInstance = panzoom(element, {
      onDoubleClick: () => false,
      zoomDoubleClickSpeed: 1,
      autocenter: true,
      transformOrigin: { x: 0.5, y: 0.5 },
      maxZoom: 1,
      minZoom: 0.3
    });

    panzomInstance.on('pan', currentInstance => {
      console.log('PANNING!', currentInstance.getTransform());
      // returns an object like this:
        {
          "x": 249.35408284820454,
          "y": 204.49944456903322,
          "scale": 0.6036430124116715
        }
    });
```

**Comment by scaryguy** [comment]
> I figured it out. The library modifies the CSS value "style.transform", which is equal to "matrix(sizeX, skewX, skewY, sizeY, posX, posY)". It is a string. I wrote a function that extracts values from the matrix and returns them as separate numbers in order to get the pan/zoom values. P.S. sizeX and sizeY are equal.

It sounds hacky, see my answer. Library already provides all the current data to us.

**Comment by Forfunckle** [comment]
Indeed, your answer is cleaner. Thanks!
