### ISSUE TITLE
 边界选项用上了，倘若用缩放，手指拉伸比较大会有误判

### ISSUE THREAD

**Issue by PassionPenguin** [anvaka/panzoom#164]
边界选项用上了，倘若用缩放，手指拉伸比较大会有误判
误判结果为缩小到最小并且将移动到边界

**Comment by anvaka** [comment]
Sorry, google translate doesn't work well for this, and my Chinese is not very good yet (dui bu qi)

Anyone can help please?

**Comment by PassionPenguin** [comment]
sorry for that... I'll translate it for u~:)

**Comment by PassionPenguin** [comment]
With the usage of the option - moving border, if you're scaling the image, and you're scaling it like from 1x to 0.1x(big motion), it will have unsatisfied responses(the image will scale to minimum size, and will move to the border...)
