### ISSUE TITLE
Panning down on mobile engages pull-to-refresh

### ISSUE THREAD

**Issue by StipeP** [anvaka/panzoom#174]
I have added this to enable touch-to-open link:

 `panzoom(element, {
  onTouch: function(e) { 
    return false;
  }
});`

but if I try to pan down, browser refreshes the page. It's like reaching to the top of facebook app and then pull to refresh. 
Is there any way around this?

**Comment by rbonomo** [comment]
I believe your solution is a HTML meta tag:
```
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
```

This app I wrote uses (a fork of) this library: [https://wayfind.arc.losrios.edu](https://wayfind.arc.losrios.edu)

**Comment by StipeP** [comment]
> <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">

No, it's not that
http://coolwall.live/
