### ISSUE TITLE
Get current zoomlevel?

### ISSUE THREAD

**Issue by martinweihrauch** [anvaka/panzoom#176]
I would like to show the current zoom level, e. g. "1.5x".
How can I retrieve the current zoom level from the library e. g. whilst scrolling the mouse wheel?

**Comment by anvaka** [comment]
You can get it from `getTransform()` api:

``` js
 console.log('scale is: ', panzoom.getTransform().scale);
```

https://github.com/anvaka/panzoom#get-current-transform-scale-offset

**Comment by findela** [comment]
maxZoom configuration not working. So is there any other way to restrict user to zoom when a threshold limit reached?
