### ISSUE TITLE
Smooth Zoom

### ISSUE THREAD

**Issue by Salman22-cloud** [anvaka/panzoom#184]
I have used panzoom for zooming specific section of page its working fine but zoom is not smooth. you can check it [here](http://travelot.pk/zoom/test.php) and what i want to be zoom smoothly like [this](https://easyzoom.com/image/95635/editors).i have set smoothScroll to true but still not working. how to make it zoom smoothly.

**Comment by Salman22-cloud** [comment]
it start blinkink when maxZoom is greater than 5.

**Comment by anvaka** [comment]
Looks like this happens outside of the library. Your css has the following transition rule:

``` css
#box {
  transition: all 0.4s linear 0s;
}
```

If you remove it the zoom is smooth as it is supposed to be.
