### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by mateja176** [anvaka/panzoom#185]
When upgrading to a major version, it would be really helpful to be able to reference a changelog. As to how the changelog is structured, create-react-app's [changelog](https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md) serves as a great example. More specifically, `panzoom` is at version `^8` in one of my repos and I wonder what the benefits are to upgrading to version 9.

**Comment by anvaka** [comment]
Agreed, I need better culture around change log generation. 

I strictly follow the tagging rule, so every version on npm has corresponding tag in the repository. You can generate the changelog by running:

```
git log v8.7.0..v9.2.1 --pretty=format:"%s [view commit](http://github.com/anvaka/panzoom/commit/%H)"
```

Here is what I've got:

9.2.1 [view commit](http://github.com/anvaka/panzoom/commit/7e2b34ae928d30c70352c87eb6f9a0f8e9bc2efb)
* respect custom controller's ctm on touch end [view commit](http://github.com/anvaka/panzoom/commit/588075cb1a93ef9681019075489da3ab512c73d2)

9.2.0 [view commit](http://github.com/anvaka/panzoom/commit/f440127e616d65287b2d7bd052ce6725c1b72599)
* rebuild [view commit](http://github.com/anvaka/panzoom/commit/54a772a2fd380b528596080463ee7af23eca96c5)
* Merge pull request #168 from TrinTragula/master [view commit](http://github.com/anvaka/panzoom/commit/0c1946d04dc6528b28a914114e96ddaaaf9a5b05)
* Public zetter for minZoom and maxZoom [view commit](http://github.com/anvaka/panzoom/commit/1b5aaadf0b90e7861a961b834ce21e9c8505783c)

9.1.0 [view commit](http://github.com/anvaka/panzoom/commit/b370e13151d46de0773c0db3b69e7c8e77c24493)
* Allow to adjust zoom speed [view commit](http://github.com/anvaka/panzoom/commit/3456a0ff88626e195e7dbe064ab99126155d2053)

9.0.0 [view commit](http://github.com/anvaka/panzoom/commit/a7955673d3c8316315d2d10477fe780151349f52)
* Account for delta speed during mouse wheel [view commit](http://github.com/anvaka/panzoom/commit/46d20ca99266e2de175ad9c892e83ca830ddb141)

8.7.5 [view commit](http://github.com/anvaka/panzoom/commit/a8bbe2b3b2f5f4576b3e41c04b0ab6a837305ef6)
* Added `disableKeyboardInteraction` definition [view commit](http://github.com/anvaka/panzoom/commit/31761dcaaabd93aa6c22b0d8ac40552b88b00f58)

8.7.4 [view commit](http://github.com/anvaka/panzoom/commit/6309a7e654b6d5d29a7b093d79368df4eb2baad5)
* rebuild [view commit](http://github.com/anvaka/panzoom/commit/90feda78ce8652434340fe6810a1ceb19cfc8685)
* patching firefox svg transformation matrix [view commit](http://github.com/anvaka/panzoom/commit/6e375d49f3a7238d633090deeeab888db0f46929)
* update fiddle link [view commit](http://github.com/anvaka/panzoom/commit/d4bcbda2a02ff0b209a7f910188a125df0bac446)
* updated versions [view commit](http://github.com/anvaka/panzoom/commit/3e690eb5086554ebcb60e1dd61729c013ce5ebec)

8.7.3 [view commit](http://github.com/anvaka/panzoom/commit/ffd7ad1d619198cc0590225b0361a0456e158ba5)
* Fixed screen transformation for svg [view commit](http://github.com/anvaka/panzoom/commit/49be4a1bd6361598b79f29fe99adc2c125d93678)
* changed the title [view commit](http://github.com/anvaka/panzoom/commit/6205e986d5379c9bcb045f63d71dbc56493946a5)
* explicitly marking events as not passive [view commit](http://github.com/anvaka/panzoom/commit/436258d9428f63508817d776d421c60440b43903)
* updated links [view commit](http://github.com/anvaka/panzoom/commit/3c5734f9a0ab0958822c9f639e5ede82e6815c5e)

8.7.2 [view commit](http://github.com/anvaka/panzoom/commit/e082555a7c9ab8ce81a60c1068c2d858d7c98448)
* Fixed center point of pinch zoom [view commit](http://github.com/anvaka/panzoom/commit/e08ec1b99baffc3f1cdf96780e426892af9d585e)
* added html tag [view commit](http://github.com/anvaka/panzoom/commit/ebf72bea92cf158a508e50519e1f8375deefb98c)

8.7.1 [view commit](http://github.com/anvaka/panzoom/commit/359230302e2ca1585a685313da59bb45ec1af258)
* Release text selection interceptor when paused [view commit](http://github.com/anvaka/panzoom/commit/4c56dc76f04580c926c2bc94230737c638c40047)
* Refactored how text selection is checked [view commit](http://github.com/anvaka/panzoom/commit/67caf21c2f94c7bd37abde3c89beb9d7d04831bd)
* Version [view commit](http://github.com/anvaka/panzoom/commit/712ea151eddc00410fc9294521787774ff3d5594)
* updated variable name [view commit](http://github.com/anvaka/panzoom/commit/0e8d88b99831401a402f585c148e17cec33b8715)
* small clean up [view commit](http://github.com/anvaka/panzoom/commit/ed37cb85f8e2ab6c19e5ebaf9a61a1d8752528f6)
* Handle burst panning [view commit](http://github.com/anvaka/panzoom/commit/9f83b0f4964665d6f67bb7228d5e0fba59a5286f)
* removed window dependency from kinetic [view commit](http://github.com/anvaka/panzoom/commit/94492b7abe333e547d0ddb1a5fb8668a63b7f47a)
* updated js style [view commit](http://github.com/anvaka/panzoom/commit/1a5e3807ac7cd1b9eb516269876d0c89823e8e91)
* Made consistent styles [view commit](http://github.com/anvaka/panzoom/commit/3354381d367ac5c37db58f75f602dd6268489338)

**Comment by mateja176** [comment]
Thank you very much for the insight. However still can't conclude what the breaking change/s are between version 8 and version 9. Moreover, looking at the log, I'd assume that it is the following commit:
```
9.0.0 view commit

Account for delta speed during mouse wheel view commit
```
However, when going through the changes associated with this commit I haven't spotted any breaking change. Is there something that I missed?

**Comment by anvaka** [comment]
The breaking change is in the user experience. It is especially noticeable when using touch scroll on OSX - prior to `v9.0.0` the zoom was monotonous, starting from `v9.0.0` it scale more naturally, proportionally to the amount of scroll events.

You would also notice change when you use a firefox browser on windows machine

**Comment by mateja176** [comment]
I don't have either a OSX or Windows machine, but I can imagine that the impact is significantly positive. On the other hand, I successfully upgraded the library in my project. Moreover, I cautiously approached the upgrade because I expected a breaking change to the API. It's funny because sometimes breaking changes slip through in minor or even patch version updates and regenerating the package-lock may lead to numerous runtime errors, which is not in accordance to semantic versioning. However, in this case the breaking change didn't actually break anything, it is however a UX improvement. Hence, do you think that the update could have been released with a minor version increase?
