### ISSUE TITLE
is it possible to zoom on click?

### ISSUE THREAD

**Issue by Pau1fitz** [anvaka/panzoom#2]
Instead of zoom on mousewheel is it possible to zoom on double click?

**Comment by anvaka** [comment]
Yup, I think I can do it. Do you want to completely disable mouse wheel for zoom? Or have both mouse wheel and double click?

**Comment by Pau1fitz** [comment]
I guess having the option to do both/disable one or the other would be cool, but if it was just adding the option to double click that would be great.

**Comment by anvaka** [comment]
Oops, forgot to update here. Double click works for zoom.
