### ISSUE TITLE
Prevent bouncing in iOS when panning/zooming

### ISSUE THREAD

**Issue by alekbless** [anvaka/panzoom#204]
Hello,

I have return false; in the onTouch callback to not preventDefault like [documented](https://github.com/anvaka/panzoom#handling-touch-events). 

This makes the browser handle my touch events on touch devices so I can interact with buttons and selects inside the panzoom element. 

As specified in README: 

"Note: if you don't preventDefault yourself - make sure you test the page behavior on iOS devices. Sometimes this may cause page to bounce undesirably." 

This happens for me as well on iOS devices, what should I preventDefault to allow only panning/zooming on the drag-area div inside panzoom element? At the moment when zooming on iOS the whole app is zoomed.

I want to disable all other touch-events other than inside my panzoom element.

**Comment by srogers** [comment]
I have a similar problem - need to let single touches bubble up for interaction with buttons, but the pinch/zoom action needs to be blocked, otherwise iOS reacts to it and starts doing app swap gesture response (which totally wrecks zoom). It worked to look at the number of touches, and stop event bubbling or not, based on that.

```
const zoomFilter = function(e) {
  if (e.touches.length === 2) {
    e.stopPropagation()
    e.preventDefault()
  }
}

document.addEventListener('touchstart', zoomFilter, { passive: false })
```

**Comment by alekbless** [comment]
Thanks @srogers 

I added an EventListener to preventDefault on touchmove inside my drag-area div

```
    document.getElementById('area').addEventListener(
      'touchmove',
      function (event) {
        event.preventDefault();
        return false;
      },
      { passive: false }
    );
```
Now the touch-events for buttons etc is registered.
