### ISSUE TITLE
dispose() does not remove mouse wheel zoom

### ISSUE THREAD

**Issue by dotnetCarpenter** [anvaka/panzoom#26]
I'm using the npm package, 4.3.1 and when calling `instance.dispose()` only pan handlers are removed. I can still zoom with the mouse wheel.

**Comment by dotnetCarpenter** [comment]
Using Chrome `65.0.3325`

**Comment by dotnetCarpenter** [comment]
Heh. I just found this comment in the beginning of `function _addWheelListener`:
>// TODO: in theory this anonymous function may result in incorrect
  // unsubscription in some browsers. But in practice, I don't think we should
  // worry too much about it (those browsers are on the way out)

**Comment by dotnetCarpenter** [comment]
After debugging the issue in [wheel](https://github.com/anvaka/wheel), I have found that the `elem` is not the same on `addEventListener` and `removeEventListener`.

I'm using vue.js, and have to investigate if it's because vue.js is changing the DOM element or if it's in panzoom. What is strange if it's vue.js, is that the other event handlers seems to be removed just fine.

**Comment by dotnetCarpenter** [comment]
Found it! wheel is listening to [`owner`](https://github.com/anvaka/panzoom/blob/master/index.js#L383) but trying to remove the wheel listener on  [`domElement`](https://github.com/anvaka/panzoom/blob/master/index.js#L361).

**Comment by dotnetCarpenter** [comment]
For everyone else with this issue, I have a published a release candidate here: https://www.npmjs.com/package/@dotnetcarpenter/panzoom

**Comment by anvaka** [comment]
Thanks for catching this and fixing it! 

This is published as `v4.4.0`

**Comment by dotnetCarpenter** [comment]
@anvaka nice that you added tests! I was wondering how to test this.

**Comment by anvaka** [comment]
you can run `npm test` in the project's folder
