### ISSUE TITLE
Need replace double click event method

### ISSUE THREAD

**Issue by danhk0612** [anvaka/panzoom#266]
When want to change double click event (zoom),
no method in now.

**Comment by 450Oucema** [comment]
Hi @danhk0612, have you found a solution for this issue ?

**Comment by danhk0612** [comment]
@450Oucema 
I'm using it by creating a function myself.

1. save initalZoom to variable

2. calculate mid pos
x = (screenSize.w - elem.dWidth * initalZoom) / 2
y = (screenSize.h - elem.dHeight * initalZoom) / 2

3. move mid pos
panzoomObj.zoomAbs(0, 0, initalZoom)
panzoomObj.moveTo(moveToPos.x, moveToPos.y)
