### ISSUE TITLE
zooming isn't smooth

### ISSUE THREAD

**Issue by christopherwalkerml** [anvaka/panzoom#279]
Running the demo or importing the library into my own code, scrolling to zoom isn't a smooth transition. Double click to zoom *is* smooth, however. Not sure what's going on here. Do I have to enable smooth zooming?
Tried on both firefox and chrome.

**Comment by anvaka** [comment]
What browser/OS are you using? Do you have a mouse or touch screen?  What demo are you referring to?

Can't reproduce this on Chrome/Firefox under OSX

**Comment by christopherwalkerml** [comment]
Both firefox and chrome, windows 10.
any of the demos, even creating a local repo and attaching an svg.
either way, I created a workaround:
`
html
<div id="outer-div">
    <div id="inner-div"></div>
</div>
`
`
css
#outer-div {
    position: absolute;
}

#inner-div {
    max-width: 100%;
    max-height: 100%;
    transition: transform 0.6s cubic-bezier(0, 0, 0.58, 1);
}
`
`js
panzoom(document.querySelector("#inner-div"), {
        maxZoom: 8,
        minZoom: 0.5,
        smoothScroll: false,
        zoomDoubleClickSpeed: 1,
        beforeMouseDown: function() {
            return true;
        },
    });

    panzoom(document.querySelector("#outer-div"), {
        smoothScroll: true,
        zoomDoubleClickSpeed: 1,
        beforeWheel: function() {
            return true;
        },
    });
`

this adds a smooth transition to the inner div, while disabling panning (smooth transition panning is bad to interact with).
and adds smoothScroll to the outer div to allow the original pan-zoom panning feature, while disabling the choppy zooming.
