### ISSUE TITLE
Programmatic pan/zoom

### ISSUE THREAD

**Issue by encrayan** [anvaka/panzoom#28]
Any method to programmatically pan/zoom?

**Comment by anvaka** [comment]
Yup. See methods here: https://github.com/anvaka/panzoom/blob/2f5602a5d9802ac4a0d595e6acf99fd51c353f25/index.js#L99-L103

**Comment by emensch** [comment]
@anvaka it seems that moveTo does not respect current zoom level when repositioning - I get weird behavior when zoomed at any scale except the default. Any suggestions?

**Comment by vivoices** [comment]
@anvaka thanks for sharing your script. I have the same issue with centerOn. It does not center on the ui element when zoomed in other than ratio 1.

**Comment by linus-amg** [comment]
@emensch @vivoices I have the same issue as you, did you find any solution in the meanwhile?

**Comment by anvaka** [comment]
@emensch, @linus-amg  would you guys be able to create a small jsbin to reproduce the error? I see [moveTo](https://github.com/anvaka/panzoom/blob/f440fe406151313dfd06b7257716f67985abf7a9/index.js#L224) doesn't change the zoom level, so I'm curious what is the behavior that is wrong?

**Comment by anvaka** [comment]
closing, as no response
