### ISSUE TITLE
Disable momentum?

### ISSUE THREAD

**Issue by sicksaduser** [anvaka/panzoom#29]
Hello. When I let go of the mouse key after dragging, the panzoom'ed object would move some residual distance. This is extremely undesired and frustrating.

I see there is no option to disable it. Probably moveByAnimation.cancel() inside panend listener would help, if only it were exposed on the module, which it isn't. Maybe amator.sharedScheduler.clearAll()? No idea how to access it from imported panzoom.js, either.

Currently I have to do
`for (var i = 1; i < 99999; i++) window.cancelAnimationFrame(i);`

**Comment by anvaka** [comment]
You can `options.smoothScroll = false` when you create a panzoom:

``` js
panzoom(scenne, {
  smoothScroll: false
})
```
