### ISSUE TITLE
Artifacts appearing when pan/zooming with audio element

### ISSUE THREAD

**Issue by mruac** [anvaka/panzoom#309]
Not sure what causes this but I don't think it is this library's fault.

If you pan/zoom the audio element in this [demo](https://jsbin.com/yebuqepaxu/edit?output), you'll notice the HTML audio element leaves behind artifacts that appear as lines that trail behind it. They seem to clear pretty quickly, so I'm not sure whether if this is a rendering issue that's caused by a low-end GPU?

https://github.com/anvaka/panzoom/assets/19784752/709f75f8-d27e-4423-b999-7c748eaf8cdd

**Comment by anvaka** [comment]
Yup, pretty sure this is not related to panzoom, seems like either a video drivers or browser specific (I couldn't reproduce this in 
* Chrome 119.0.6045.159 
* FireFox 115.0.2 
* FireFox 119.0.1

I tested in OSX 12.7.1 (21G920) with Intel Iris Graphics 550 1536 MB
