### ISSUE TITLE
initial zoom and position do not work

### ISSUE THREAD

**Issue by xanthius** [anvaka/panzoom#31]
when I use the default position and scale function the way it is described, it only changes the default y position but nothing else. additionally, the yposition isnt even what I set it to. when I use .zoomAbs(300,500,0.2); it sets the default matrix to:  matrix(1, 0, 0, 1, 0, 400); instead of  matrix(0.2, 0, 0, 0.2, 300, 500); like you'd expect. If i change the zoomAbs numbers it the resulting y position changes but that's all

**Comment by xanthius** [comment]
I've done some more testing and the scale works if the first value is set to 0 and the second value is 31 or above but otherwise no initial scaling is set.

**Comment by xanthius** [comment]
when i change the x and y offsets to 0 and just play with the scaling some numbers work but not always. i tried with 0,0,0.2 and it worked then i changed ti to 0,0,0.1 and it didnt s i went back to 0,0,0.2 and that wasnt working this time around. even when it was working the x and y values were at a few hundred each which makes no sense. the zoomAbs seems really off

**Comment by Jasiudab** [comment]
Hey, @xanthius can you please elaborate on what autocenter you are talking about? I have a very similar issue and can't get it to work

**Comment by zekedroid** [comment]
Same

**Comment by Salitehkat** [comment]
> when I use the default position and scale function the way it is described, it only changes the default y position but nothing else. additionally, the yposition isnt even what I set it to. when I use .zoomAbs(300,500,0.2); it sets the default matrix to: matrix(1, 0, 0, 1, 0, 400); instead of matrix(0.2, 0, 0, 0.2, 300, 500); like you'd expect. If i change the zoomAbs numbers it the resulting y position changes but that's all

Please, is there any fix to this. Intial zoom does not work. Thank so much.
