### ISSUE TITLE
How to always zoom from center?

### ISSUE THREAD

**Issue by cibulka** [anvaka/panzoom#34]
In examples you have provided, I've noticed that (percieved?) `transform-origin` for the zoom is based of current cursor position. Would it be possible to force the `transform-origin` to always be set on `center center`? 

I've tried to look around your code, even play with some variables, but unfortunately I wasn't able to find where this is determined. Thanks in advance!

**Comment by ethorz** [comment]
+1. Yeah, I also encountered such a problem.

**Comment by ingelaro** [comment]
+1. It would be nice to handle this somehow, cause with different image sizes it's even more pain. Also option to reset controller to initial state would be awesome. A lot of use cases when there is need to zoom in-out and reset state are really hard to handle.

**Comment by kmarci95** [comment]
+1

**Comment by rmbar** [comment]
+1 for a mode where zoom in/out does not care where the moues is positioned on the screen.

**Comment by rsavinsky** [comment]
I was able to implement a reset button, but setting the transform style on the element.
`$('.zoom-reset').on('click', function() {
    $('#panzoom').css('transform', 'matrix(1, 0, 0, 1, 0, 0)');
  });`

**Comment by BiLosxD** [comment]
For centering when zooming in or out. I have this codes:

**VUE JS**
`
                            <panZoom @init="panZoomInit" :options="{
                                bounds: true,
                                boundsPadding: 0.2,
                                minZoom: 0.2,
                                maxZoom: 1,
                                zoomDoubleClickSpeed: 1,
                                beforeWheel: panZoomBeforeWheel,
                                onDoubleClick: panZoomDoubleClick,
                                smoothScroll: false,
                                onTouch: panZoomTouch
                            }">
                                 <p>Your Content Here</p>
                            </panZoom>

`

**JS**
`
var zoomCtr = 0.6

panZoomInit (instance, id) {
                const me = this
                /** Get the current dimension of the panzoom container */
                let planWidth = document.querySelector('.plan_wrapper').getBoundingClientRect().width
                let planHeight = document.querySelector('.plan_wrapper').getBoundingClientRect().height

                /** Default view upon initializing the panzoom */
                instance.zoomAbs(planWidth / 2, planHeight / 2, 0.6)
                planWidth = instance.getTransform().x
                planHeight = instance.getTransform().y

                document.getElementById('zoom_in').addEventListener('click', function(e) {
                    customZoom(instance, 'in')
                })
                document.getElementById('zoom_out').addEventListener('click', function(e) {
                    customZoom(instance, 'out')
                })
                document.getElementById('reset').addEventListener('click', function(e) {
                    if (zoomCtr >= 1) {
                        zoomCtr = 0.6
                    }
                    if (zoomCtr <= 0.99999) {
                        zoomCtr = 1.4
                    }
                    instance.getTransform().x = planWidth
                    instance.getTransform().y = planHeight
                    instance.getTransform().scale = 0.6
                    document.querySelector('.plan_wrapper').style.transform = `matrix(0.6, 0, 0, 0.6, ${planWidth}, ${planHeight})`
                })
            },

customZoom (instance, type) {
                const me = this
                /** Get original dimension of the panzoom container */
                let planWidth = document.querySelector('.plan_wrapper').offsetWidth
                let planHeight = document.querySelector('.plan_wrapper').offsetHeight
                switch (type) {
                    case 'in':
                        if (zoomCtr <= 0.99999) {
                            zoomCtr = 1.4
                        }
                        instance.smoothZoom((planWidth / 2) + zoomCtr, (planHeight / 2) + zoomCtr, me.zoomCtr)
                        zoomCtr += 0.2
                        break
                    case 'out':
                        if (zoomCtr >= 1.0) {
                            zoomCtr = 0.6
                        }
                        instance.smoothZoom((planWidth / 2) + zoomCtr, (planHeight / 2) + zoomCtr, me.zoomCtr)
                        zoomCtr -= 0.2
                        break
                }
            }

`

**Comment by anvaka** [comment]
Added in `v8.5.0`. To fix panzoom to the middle of the screen, use the following code:

``` js
let panzoomInstance = panzoom(element, {
  transformOrigin: {x: 0.5, y: 0.5}
});
```

**Comment by anvaka** [comment]
See example here https://anvaka.github.io/panzoom/demo/center-center.html
