### ISSUE TITLE
Is there a way to disable scaling for childelements?

### ISSUE THREAD

**Issue by BHuys** [anvaka/panzoom#35]
I would like to use this library as a map with markers. When a marker is clicked it should open a popup container on this specific position which doesn't scale and reposition when zooming or panning, keeping the content readable at all times.

**Comment by anvaka** [comment]
Maybe you could open the container marker in absolutely positioned div, which is outside of the zoomable area? Would this work for your use case?

**Comment by anvaka** [comment]
Please let me know if this still needs help
