### ISSUE TITLE
The current version of jsdom and tap are have vulnerable dependenceis

### ISSUE THREAD

**Issue by moyass** [anvaka/panzoom#37]
Hey!

You are currently using jsdom@11.6.2 which depends on a vulnerable version of request -> stringstream
Updating the version to 11.12.0 fixes this issue.

**Comment by anvaka** [comment]
Thanks, I've updated the jsdom. What is the vulnerability? Is `tap` also affected?

**Comment by anvaka** [comment]
Thanks! Both dependencies are updated and published as `v6.1.4`
