### ISSUE TITLE
Ger current zoom scale

### ISSUE THREAD

**Issue by tweakitguy** [anvaka/panzoom#39]
Just curious, is this the best way to get the current zoom scale?  I want to hide/show elements based on zoom level.

```
document.body.addEventListener('zoom', function(e) {
        var map = document.getElementById("tick-map").children[0];
        var zoomLevel = map.style.transform.split(',')[0].replace("matrix(","");
}, true);
```

**Comment by anvaka** [comment]
You can use `panzoom.getTransform()` to get the transformation matrix. `scale` property would give you want you want.

Be warned thought - do not modify the object that you receive from `getTransform` - that would result in unpredictable behavior.
