### ISSUE TITLE
Setting an initial zoom

### ISSUE THREAD

**Issue by rjgrazioli** [anvaka/panzoom#4]
Would be nice to be able to set an initial transform value on the scene:

```
panzoom(document.getElementById('g4'), {
    initialZoom: 2
});
```

**Comment by anvaka** [comment]
Interesting! Is this the same as:

``` js
var zoomer = panzoom(document.getElementById('g4'));
zoomer.zoomAbs(0, 0, 2);
```
?

**Comment by anvaka** [comment]
Closing this. Please let me know if you need more support here

**Comment by UltraCakeBakery** [comment]
It feels kinda stupid to call a function to set the start position after 'PanZoom' has been initialized. Can someone look into adding it to the initial 'settings' parameter? Maybe i'll make a PR for it later.
