### ISSUE TITLE
panzoom prevents developer's double click events in the app

### ISSUE THREAD

**Issue by MohammedAbdulMateen** [anvaka/panzoom#46]
First of all thanks for making such a great plugin!

The following is the code I am using,

```
        // just grab any DOM element
        var area = document.querySelector('.faqdesigner');

        // And pass it to panzoom
        panzoom(area, {
            zoomDoubleClickSpeed: 1
        });

        // this is the double click event
        $('.appcontainer').on('dblclick', '.faqnode', onNodeDblClick);
```

but double click on elements is not firing because of panzoom plugin, so I investigated and checked the source code, I see a lot of

```
e.preventDefault();
e.stopPropagation();
```

even inside `function onDoubleClick(e) { ... }` which I commented and my double click event gets fired

it is restricting and interfering with the developers code, it may be nice to have it configurable like switch on or off through plugin settings

could you please have a look

**Comment by MohammedAbdulMateen** [comment]
The same issue exists with click events also

**Comment by anvaka** [comment]
Thank you for the suggestion!

Starting from `v6.3.0`, you can do this by passing `onDoubleClick(e)` event handler that returns `false`:

``` js
panzoom(document.getElementById('g4'), {
  onDoubleClick: function(e) {
    // `e` - is current double click event.

    return false; // tells the library to not preventDefault, and not stop propagation
  }
});
```

Please let me know if this works for you.

**Comment by MohammedAbdulMateen** [comment]
@anvaka yes it works, thanks a lot 👍

**Comment by el3ment** [comment]
panzoom appears to still handle the double click as a zoom though... as far as I can tell there does not seem to be a way to disable the zoom-on-double-click feature

**Comment by dota2Pro** [comment]
> panzoom appears to still handle the double click as a zoom though... as far as I can tell there does not seem to be a way to disable the zoom-on-double-click feature

```
panzoom(element, {
  zoomDoubleClickSpeed: 1, 
});
```

Disables Double click zoom
