### ISSUE TITLE
[FEATURE] Emit events

### ISSUE THREAD

**Issue by vogloblinsky** [anvaka/panzoom#54]
Is it possible to emit events on instance ?
- zooming
- paning

**Comment by anvaka** [comment]
I realized this was not documented well. And also thought that my previous approach to events notification was bound to DOM. I dropped DOM as a way to propagate events, and use javascript events instead. This should be available starting from `7.0.2`.

Here is updated documentation: https://github.com/anvaka/panzoom#events-notification - please let me know if this works for you (likely you need `pan` and `zoom` events).

**Comment by vogloblinsky** [comment]
It works, thanks
