### ISSUE TITLE
Mobile users

### ISSUE THREAD

**Issue by mattdax** [anvaka/panzoom#6]
Hi I have noticed that the pan zoom does not allow for links to be opened on mobile. Just a heads up.

**Comment by odai-alali** [comment]
check this docs
https://github.com/anvaka/panzoom#handling-touch-events

just add `onTouch` handler to your options

**Comment by alextappin** [comment]
Hi, wondering if there is a workaround or any progress that has been made on this? Encountering the same issue.

**Comment by anvaka** [comment]
See https://github.com/anvaka/panzoom/issues/12#issuecomment-373251144 . Please let me know if that doesn't work.
