### ISSUE TITLE
use of 'let' breaks uglifyjs 

### ISSUE THREAD

**Issue by bigfish** [anvaka/panzoom#64]
I'm getting the build error

ERROR in index.js from UglifyJs
Unexpected token: name (clientRect) [./node_modules/panzoom/index.js:146,0][index.js:57353,8]

caused by line 146:

  let clientRect = owner.getBoundingClientRect()

since the rest of the module is es5, I believe it should be 'var clientRect...' ?

**Comment by anvaka** [comment]
doh. Sorry about that. Fixed in `v7.1.1`
