### ISSUE TITLE
Patch for bug in zoom-point offsets for pinch zoom

### ISSUE THREAD

**Issue by lildoggie** [anvaka/panzoom#67]

**Comment by lildoggie** [comment]
The zoom point is wrong for pinch zooming on DOM elements in offset containers (mousewheel zooming works fine).  This patch to handleTouchMove() fixes the problem:

       mouseX = (t1.clientX + t2.clientX)/2
       mouseY = (t1.clientY + t2.clientY)/2

      // original code
       //publicZoomTo(mouseX, mouseY, scaleMultiplier)
  
       // new code (bug fix)
      var ownerRect = owner.getBoundingClientRect();
      var offsetX = mouseX - ownerRect.left
      var offsetY = mouseY - ownerRect.top
      publicZoomTo(offsetX, offsetY, scaleMultiplier)
  
        pinchZoomLength = currentPinchLength
        e.stopPropagation()
        e.preventDefault()

Sorry, I'm new to github and don't know the traditional etiquette for suggestions like this.  But hopefully a patch can be included in the next release.  Thanks for the great work.

**Comment by ims** [comment]
Can confirm it works. Thank you

**Comment by anvaka** [comment]
Sorry, I'm missing something - what are the steps to reproduce the bug? Do you have a link to try?

**Comment by TimoKunze** [comment]
@anvaka On a multi touch display I had this issue a couple of times when pinching. I pinch close to the middle of the zoomable element and it zooms, but also jumps towards the top-left corner.
After I applied this patch, I never had this issue again, so it seems to work.
I think you won't see the issue, if the container starts at 0,0 of the screen.

**Comment by anvaka** [comment]
Thank you all for pointing out! Sorry it took me so long to get to it, but it should be fixed starting from `v8.7.2`

**Comment by anvaka** [comment]
Please let me know if this still exists.
