### ISSUE TITLE
Zoom "Step"

### ISSUE THREAD

**Issue by ct5845** [anvaka/panzoom#70]
Is there a way to set a zoom "Step"? 

e.g. { zoomStep: 0.1 } // 10% zoom steps.

**Comment by anvaka** [comment]
Yes. See [Zoom Speed](https://github.com/anvaka/panzoom#zoom-speed) section in the readme.

**Comment by ct5845** [comment]
Brilliant, sorry i assumed that was animation speed related.

**Comment by ct5845** [comment]
So i thought it might be floating point, but looking into the code it seems zoom speed always works on the previous transform;

e.g. { zoomSpeed: 0.05 }

(1) The first "zoom in" ratio = 1 * 1.05 = 105% of original canvas.

(2) The second "zoom in" however will zoom to 105% of the already zoomed canvas; e.g. 1.05 * 1.05 = 110(.25)%

(3) The third "zoom in"... 1.1025 * 1.05 = 115(.76)% = 116%.

Is there anyway to make it respect the original size? so it goes 100% -> 105% -> 110% -> 115% and so on?

In my scenario i can't just "get back" to 100%, 3 zoom outs, 

(4) Zoom out... 115.76... * 0.95 =  1.0997....

(5) Zoom out... 1.0997 * 0.95 = 1.04475...

(6) Zoom out... 1.04476.. * 0.95 =0.99...

Fair enough if this is intended for smooth scrolls etc. just wanted to check!
