### ISSUE TITLE
Restrict viewport

### ISSUE THREAD

**Issue by MartinMuzatko** [anvaka/panzoom#71]
Hello! Is there a way to restrict the pan to only happen within the element? I don't want to enable users to hide the element.

**Comment by tomhooijenga** [comment]
There is an undocumented option that can be passen when creating the panzoom object.
Pass a boolean to use the bounding box of the parentElement of `el`. You can also pass your own bounds.

```js
panzoom(el, {
    bounds: true
 });
```
```js
panzoom(el, {
    bounds: {
        top: 0,
        bottom: 0,
        right: 0,
        left: 0
    }
});
```

**Comment by MartinMuzatko** [comment]
thank you a lot! will test this :)

**Comment by mateja176** [comment]
> There is an undocumented option that can be passen when creating the panzoom object.
> Pass a boolean to use the bounding box of the parentElement of `el`. You can also pass your own bounds.
> 
> ```js
> panzoom(el, {
>     bounds: true
>  });
> ```
> 
> ```js
> panzoom(el, {
>     bounds: {
>         top: 0,
>         bottom: 0,
>         right: 0,
>         left: 0
>     }
> });
> ```
> 
> There is also an option `boundsPadding` (number, default 0.05), which shrinks the given `bounds` by the given ratio.

Top and left bounds work just as expected, however right and bottom bounds do not take effect as can be seen [here](https://stackblitz.com/edit/react-canvas-panzoom-zcjbce)
You can pan passed the `right` border and the `bottom` border despite having set:
```
      bounds: {
        left: 0,
        top: 0,
        right: 0,
        bottom: 0,
      },
```

**Comment by rosalynpoort** [comment]
I had the same issue where right and bottom bounds did not work. Here is my solution:

`panzoom_instance.on('transform', (e) => {
          var transformObject = panzoom_instance.getTransform();
          var panzoom_wrapper = $('.panzoom-wrapper')[0];
          var panzoom_el = $('.panzoom')[0];
          var panzoom_el_width = (panzoom_el.offsetWidth * transformObject.scale);
          var panzoom_el_height = (panzoom_el.offsetHeight * transformObject.scale);
          var max_x = panzoom_wrapper.offsetWidth - panzoom_el_width;
          var max_y = panzoom_wrapper.offsetHeight - panzoom_el_height;

          if( transformObject.x > 0 ){
            // console.log('left less than 0');
            panzoom_instance.moveTo(0,transformObject.y);
          } else if(transformObject.x < max_x){
            // console.log('left more than max');
            if(panzoom_el_width <= panzoom_wrapper.offsetWidth){
              panzoom_instance.moveTo(0,transformObject.y);
            } else {
              panzoom_instance.moveTo(max_x,transformObject.y);
            }
          }

          if( transformObject.y > 0 ){
            // console.log('top less than 0');
            panzoom_instance.moveTo(transformObject.x, 0);
          } else if(transformObject.y < max_y){
            // console.log('bottom more than max');
            if(panzoom_el_height <= panzoom_wrapper.offsetHeight){
              panzoom_instance.moveTo(transformObject.x, 0);
            } else {
              panzoom_instance.moveTo(transformObject.x, max_y);
            }
          }
        });`

**Comment by BakaloMykhailo** [comment]
//html
<div class="wrapper">
        <div class="container">
            <img class="image" src="../panzoom-p/images/balloon.png" alt="balloon">
        </div>
    </div>
//css
body {
    margin: 0;
    height: 100vh;
}
.wrapper {
    position: relative;
    max-width: 1200px;
    margin: 0 auto;
    overflow: hidden;
    height: 100%;
}
.container {
    width: 4000px;
}
.image {
    width: 100%;
    height: 100%;
}
//js
const mapWrap = document.querySelector('.wrapper');
const element = document.querySelector('.container');

const instance = panzoom(element, {
    maxZoom: 3,
    minZoom: 0.5,
    bounds: {
        left: 0,
        top: 0,
        right: 0,
        bottom: 0,
      },
});


instance.on('transform', (e) => {
    const transformObject = instance.getTransform();
    const panzoom_el = element;
    
    const qX = -panzoom_el.offsetWidth * transformObject.scale + mapWrap.offsetWidth;
    const qY = -panzoom_el.offsetHeight * transformObject.scale + mapWrap.offsetHeight;
    if ( transformObject.x < qX ) {
        instance.moveTo(qX , transformObject.y);
    }
    if ( transformObject.y < qY ) {
        instance.moveTo(transformObject.x, qY);
    }
} )

**Comment by Pimenovvalerii** [comment]
//html
<div class="wrapper">
        <div class="container">
            <img class="image" src="..." alt="balloon">
        </div>
    </div>
//css
body {
    margin: 0;
    height: 100vh;
}
.wrapper {
    position: relative;
    max-width: 1200px;
    margin: 0 auto;
    overflow: hidden;
    height: 100%;
}
.container {
    width: 4000px;
}
.image {
    width: 100%;
    height: 100%;
}
//js
const mapWrap = document.querySelector('.wrapper');
const element = document.querySelector('.container');

const instance = panzoom(element, {
    maxZoom: 3,
    minZoom: 0.5,
    bounds: {
        left: 0,
        top: 0,
        right: 0,
        bottom: 0,
      },
});


instance.on('transform', (e) => {
    const transformObject = instance.getTransform();
    const panzoom_el = element;
    
    const qX = -panzoom_el.offsetWidth * transformObject.scale + mapWrap.offsetWidth;
    const qY = -panzoom_el.offsetHeight * transformObject.scale + mapWrap.offsetHeight;
    if ( transformObject.x < qX ) {
        instance.moveTo(qX , transformObject.y);
    }
    if ( transformObject.y < qY ) {
        instance.moveTo(transformObject.x, qY);
    }
} )

**Comment by Pimenovvalerii** [comment]
//css
body {

1. 

    margin: 0;
    height: 100vh;
}
.wrapper {
    position: relative;
    max-width: 1200px;
    margin: 0 auto;
    overflow: hidden;
    height: 100%;
}
.container {
    width: 4000px;
}
.image {
    width: 100%;
    height: 100%;
}
//js
const mapWrap = document.querySelector('.wrapper');
const element = document.querySelector('.container');

const instance = panzoom(element, {
    maxZoom: 3,
    minZoom: 0.5,
    bounds: {
        left: 0,
        top: 0,
        right: 0,
        bottom: 0,
      },
});


instance.on('transform', (e) => {
    const transformObject = instance.getTransform();
    const panzoom_el = element;
    
    const qX = -panzoom_el.offsetWidth * transformObject.scale + mapWrap.offsetWidth;
    const qY = -panzoom_el.offsetHeight * transformObject.scale + mapWrap.offsetHeight;
    if ( transformObject.x < qX ) {
        instance.moveTo(qX , transformObject.y);
    }
    if ( transformObject.y < qY ) {
        instance.moveTo(transformObject.x, qY);
    }
} )

**Comment by MartinMuzatko** [comment]
I moved to LeafletJS, which fulfills what I wanted to abuse this module for.
While LeafletJS needs a ton of work to be used in a modular fashion, I hope projects like this keep working on a proper solution for this :) thanks
