### ISSUE TITLE
pause resume not working

### ISSUE THREAD

**Issue by dominicdev** [anvaka/panzoom#74]
I was using svg, but it was not working, any idea? i try to log but no error found

**Comment by dominicdev** [comment]
I'm using panzoom.js

**Comment by dominicdev** [comment]
It seems the releaseEvents was not working at all,event it was call not sure why, im using ndoejs electron btw

**Comment by anvaka** [comment]
Do you still see the error? Can you share an example to reproduce this?

**Comment by naseemshah** [comment]
I have the same issue, but only on Mobile. Panzoom on Mouse works after panzoom.resume(); but not for touch.
