### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by CosteaPaul** [anvaka/panzoom#76]
Trying to use panZoom in firefox and getting the following when trying to apply it to an SVG like:
panzoom($("#container").find('svg').find('g')[0])

Console:

TypeError: screenCTM is null 
Stack trace: 
initTransform@https://cdn.rawgit.com/anvaka/panzoom/v6.1.3/dist/panzoom.min.js:1:19912 createPanZoom@https://cdn.rawgit.com/anvaka/panzoom/v6.1.3/dist/panzoom.min.js:1:1856

Works fine on Chrome...

**Comment by smeijer** [comment]
Demo seems to work here https://anvaka.github.io/panzoom/demo/dom.html

**Comment by CosteaPaul** [comment]
Was calling panzoom before the page had focus which seems to be a problem in firefox and not Chrome. Moved the initialization and that works. Thanks!
