### ISSUE TITLE
How to add a center button

### ISSUE THREAD

**Issue by verilog15** [anvaka/panzoom#81]
I would like to add a center button. How to do it? I saw that we can use the `centerOn` option but it asks for `ui` (not sure what does it mean). Would love to see a real example of use.

Thank you.

**Comment by anvaka** [comment]
Can you elaborate what happens when user clicks on that button?

**Comment by anvaka** [comment]
Going to close this one as no response. 

Otherwise you can move to any point by using `moveTo()`, `zoomAbs()` functions. Also see https://github.com/anvaka/panzoom/issues/69#issuecomment-484351470

**Comment by andrewvarga** [comment]
I'm missing this too. There is an "autocenter" option which works well, but no autoCenter function I can call once PanZoom is initialized.
The only similar I found was centerOn but that only seems to work with SVGs.

There is one possible way to do by using "showRectangle" with a manually calculated Rect. but even that doesn't auto refresh the component, you need to interact with it to update itself.

**Comment by anvaka** [comment]
@andrewvarga I'm trying to understand what that button would do. What happens when you click on it? Can you give me a scenario please?

**Comment by andrewvarga** [comment]
So if I have a div that I passed to "createPanZoom" which is 500 x 500 px and I have an image inside it which is 1200 * 600, using "autocenter" option will make the image smaller to fit inside the div.
But then the user can zoom / pan and I want to add a button which will reset to the initial state before the user started interacting.
I can do this by saving the transform after "createPanZoom" and restoring, or calling "ShowRectangle" with the size of my image, but it would be much simpler to just have a method "fitContent()".
