### ISSUE TITLE
Zooming and panning too fast on iPad

### ISSUE THREAD

**Issue by AnReZa** [anvaka/panzoom#86]
I'm using your plugin on an iPad. There, panning the element with your fingers moves the element much faster as your fingers. Also, zooming is very sensitive. Is there a way to make it feel more natural?

**Comment by anvaka** [comment]
Can you try here https://anvaka.github.io/panzoom/demo/attach-via-script.html - does this still seem to fast/unnatural for you?

I just tried on a touch enabled device - and it feels pretty normal to me. If the demo above looks normal to you as well but your code behaves differently - we'd need to find a difference. Maybe there is something else going on (like multiple instances of panzoom working on the same container)?

**Comment by AnReZa** [comment]
Unfortunately, it feels exactly the same. The zoom is way too fast. You just pinch your fingers a few millimeters and it zooms quite much. Normally, I would expect that the two points under your finger follow their movement. Exactly the same behavior as the gallery apps on any Android or iOS device. This library, however, scales that up at least three times, so it zooms about three times the speed your fingers move. This might be a good behavior in some situations, where you want to zoom into really big images, but for normal photos, it misses a lot of percision.

**Comment by anvaka** [comment]
Ah, I see what you mean and your request makes total sense!

Starting from version `8.0.0` of this library, pinch speed should match the fingers distance (by default). If that is too slow, you can adjust the pinch speed with `pinchSpeed` option:

```
panzoom(element, {
  pinchSpeed: 2 // zoom two times faster than the distance between fingers
});
```

If you need this behavior in older version of the library (`4.x .. 7.x`) you can use `realPinch: true` option which was made available by @odai-alali in this PR: https://github.com/anvaka/panzoom/pull/18

Hope this works!

**Comment by AnReZa** [comment]
I've updated to `8.0.0` and it works perfectly. There is still a little bit of "overdrive", but it's barely noticable. I don't know, if that's normal or a specific issue of the iPad Pro.

But thank you very much for your good work!

**Comment by anvaka** [comment]
thank you!
