### ISSUE TITLE
height/width error 

### ISSUE THREAD

**Issue by ibrahimhajjaj** [anvaka/panzoom#87]
Hey, thanks for the plugin it's soo good :) 

I have svg grouped by g tag, when the plugin is disabled the svg height and width looks good but when the plugin is enabled the width/height is of the svg is too small!

**plugin enabled** 
![image](https://user-images.githubusercontent.com/23178074/55818917-68546600-5b00-11e9-87e6-629102c2a343.png)

**plugin disabled**
![image](https://user-images.githubusercontent.com/23178074/55818972-83bf7100-5b00-11e9-8242-e80ad2f3499e.png)

so how I can fix this?!

and let me know if there is a way to initialise the plugin only on mobile devices.

thanks 👍

**Comment by anvaka** [comment]
Please provide a demo on https://jsbin.com/  to reproduce the error

**Comment by anvaka** [comment]
no response, closing
