### ISSUE TITLE
Click(tap/touch) is not working on touch devices!

### ISSUE THREAD

**Issue by vijilov** [anvaka/panzoom#92]
I am creating an interactive SVG, on click a popup will show up.

This is working fine on PC, however in the touch/click event the popup is not working on iPad & Android devices.

This popup is showing if I enable touch event using call back function,  but Panning and Zooming on these devices are not working properly. 

How can I rectify this issue? Any help is appreciated.

**Comment by anvaka** [comment]
Can you please create a https://jsfiddle.net/ to reproduce it?

**Comment by vijilov** [comment]
Please find the same here, 
https://jsfiddle.net/vijilov/d986x4qk/

The click is not working on iPad/ any touch devices. 
Also please check the Zoom & Reset button functionality also.

Thanks!

**Comment by anvaka** [comment]
Thanks for the demo! With these little changes it should work:

``` js
// added `touchend`:
$(".each-row").on("click touchend",function(){
  alert("Clicked on "+ $(this).data('name'));
});

var area = document.getElementById('zoomPanCont');
var instance  = panzoom(area, { 
  bounds: true,
  maxZoom: 1.55,
  minZoom: .8,
  zoomDoubleClickSpeed: 1,
 // no need to add onTouch here.
});
```

https://jsfiddle.net/k926u04r/

`click` event is somewhat fragile on touch-enabled devices (e.g. see this question [onClick not working on mobile (touch)](https://stackoverflow.com/questions/22015908/onclick-not-working-on-mobile-touch))

**Comment by vijilov** [comment]
Thank you for your help. It is working on touch devices now.
