### ISSUE TITLE
Feature Request: smoothMove

### ISSUE THREAD

**Issue by rbonomo** [anvaka/panzoom#93]
Hey man, I'd really love to have this feature in this library. Imagine the smoothZoom, but smoothMove instead (has nice animation and pans to specified position). There is moveTo, which is great, but I'd like to have smoothMove as well. There is zoomTo and smoothZoom, so I think it would be fitting if there was a smoothMove as well. Is this an easy implementation for you? I was planning on digging through the source and doing my own implementation for it this weekend if you weren't up for the task.

**Comment by rbonomo** [comment]
Show me your smooth moves!

**Comment by rbonomo** [comment]
panzoom.moveBy(dx, dy, 1) Does this perfectly for me. But I had to look into the source to find that out. Awesome lib man :) Thanks for being AWESOME

**Comment by blahmonkey** [comment]
> panzoom.moveBy(dx, dy, 1) Does this perfectly for me. But I had to look into the source to find that out. Awesome lib man :) Thanks for being AWESOME

@anvaka Please add this to the README, it would be helpful.
