### ISSUE TITLE
Get Zoom Min/Max

### ISSUE THREAD

**Issue by tuckergordon** [anvaka/panzoom#94]
It would be great to be able to get the min/max zoom from a PanZoom instance. Currently it looks like you can set them in the options, but have no way of accessing this. One potential use case is adding _disabled_ styles to zoom +/- buttons, which would require knowing what the bounds are/when they've been reached

**Comment by edgarsn** [comment]
Totally agree. Currently this is not possible.

**Comment by anvaka** [comment]
Good suggestion. Added `getMinZoom()` and `getMaxZoom()` starting from `v8.1.0`
